### ISSUE TITLE
需要引入H5外观设计师

### ISSUE THREAD

**Issue by grapewheel** [welkinwong/nodercms#1]
基于nodejs的CMS，noder算做得很出色了，但用得NODEJS的都是技术牛人，往往忽略了外观模板，只要引入H5外观设计师协助，noder才能广泛使用起来，并进行收费，因为网站说白了都是外观模板为先，功能再强大也不会超越那些

**Comment by grapewheel** [comment]
本来我想用在客户那里，发现没有模板。。。又不想花时间去搞，支持不了你了

**Comment by welkinwong** [comment]
@grapewheel 很好的提议，之后会考虑增加几个默认模板，但是 NoderCMS 有各种自定义字段（像推荐位和扩展属性），很难做很通用模板，因此最好还是使用者自行套模板 : )
