### ISSUE TITLE
在macos上运行的一个小问题

### ISSUE THREAD

**Issue by newpanjing** [welkinwong/nodercms#13]
在启动的时候log4js会提示找不到文件或目录，要改成酱紫：
>var path = require("path");
var dir = path.join(__dirname, '../');
module.exports = {
    appenders: [
        {
            type: 'console'
        },
        {
            type: 'dateFile',
            category: 'access',
            filename: dir+'logs/access/access',
            pattern: '-dd--hh.log',
            alwaysIncludePattern: true
        },
        {
            type: 'dateFile',
            category: 'system',
            filename: dir+'logs/system/system',
            pattern: '-dd.log',
            alwaysIncludePattern: true
        },
        {
            type: 'dateFile',
            category: 'database',
            filename: dir+'logs/database/database',
            pattern: '-dd.log',
            alwaysIncludePattern: true
        },
        {
            type: 'logLevelFilter',
            level: 'ERROR',
            appender: {
                type: 'dateFile',
                filename: dir+'logs/errors/error',
                pattern: '-MM-dd.log',
                alwaysIncludePattern: true
            }
        }
    ],
    replaceConsole: true
};

**Comment by welkinwong** [comment]
收到，这个我也更新一下，没从程序目录启动会这样子
