### ISSUE TITLE
mongodb auth

### ISSUE THREAD

**Issue by ciey** [welkinwong/nodercms#15]
安装过程中连接mongodb需要用户名和密码，能否设为可选，一般开发环境下monogodb是不需要认证的。

还有连接数据库有个ERROR：DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client

**Comment by welkinwong** [comment]
收到，确实有这个需要
