### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by yuzedong** [welkinwong/nodercms#17]
admin文件夹下的main.js中结构是这样：
`angular.module('nodercms'，[....])`
`      .config(.....)`
`      .run(['checkSign', '$templateCache', function (checkSign) {`
`              console.log('111'); `
`              checkSign();`
`}]);`
请问为什么我在这个地方log(111) node控制台中打印不出来？我主要想看看这个run中是在什么时候执行的。谢谢！

**Comment by welkinwong** [comment]
这是因为src下的文件被编译压缩到/public/下

如果你要使你的更改生效：
gulp build 生产环境编译
gulp 开发环境编译（会监控文件改动）
