### ISSUE TITLE
非顶级分类下新增链接失败

### ISSUE THREAD

**Issue by suffrajet** [welkinwong/nodercms#2]
链接类型的分类只能加载顶级分类下，如果在频道或者栏目下新增就会报错：

categories.controller.js { type: 'system', error: '上级分类不存在' }

**Comment by welkinwong** [comment]
@suffrajet  感谢提供，下个版本将修复这个BUG

**Comment by welkinwong** [comment]
@suffrajet 在 v1.3.1 版本中已经修复了这个问题
