### ISSUE TITLE
nodercms如何嵌入到nuxt.js工程？

### ISSUE THREAD

**Issue by yasz** [welkinwong/nodercms#29]
我的ui是基于vue/nuxt.js开发的，如何将cms嵌入到我已有的ui框架内？

**Comment by welkinwong** [comment]
你想把管理后台嵌入到已有框架还是网站前端？，如果是管理后台的话，模板文件在/src/views/下，如果是网站前端的话，你可以拷贝/public/themes/default/一份，单独自己实现一个主题
