### ISSUE TITLE
如何生成html

### ISSUE THREAD

**Issue by bage2017** [welkinwong/nodercms#32]
请教一下，模板写好后，如何像hugo那样将网站前端批量生成html

**Comment by welkinwong** [comment]
NODERCMS 是服务端渲染的，对于搜索引擎或用户来说就是静态的html和css

如果是希望放到CDN等或者用来加速访问的话，目前还不支持生成静态文件（你可以自己二次开发，nodercms结构还是蛮灵活的）

发自我的iPhone

**Comment by bage2017** [comment]
额，好的，谢谢，还有个问题就是mongodb必须要设置密码才能配置哈？




| |
何勇
邮箱：hxiaoxuey@163.com
|

签名由 网易邮箱大师 定制

在2019年10月06日 22:46，Welkin Wong 写道：
NODERCMS 是服务端渲染的，对于搜索引擎或用户来说就是静态的html和css

如果是希望放到CDN等或者用来加速访问的话，目前还不支持生成静态文件（你可以自己二次开发，nodercms结构还是蛮灵活的）

发自我的iPhone

**Comment by welkinwong** [comment]
是的哈，出于安全性考虑，需要设置密码，关于mongodb设置用户及密码可以参考这篇教程：http://www.nodercms.com/help/installation/windows-xia-an-zhuang-mongodb-jiao-cheng

发自我的iPhone
