### ISSUE TITLE
Centos安装问题

### ISSUE THREAD

**Issue by qinaichen** [welkinwong/nodercms#5]
想要在centos上安装发布，请问需要安装哪些依赖包！

**Comment by welkinwong** [comment]
Hello，你可以按照下方步骤

> 首先你需要 Node.js 环境和一个带有用户名密码的 MongoDB 数据库

1. 先安装图形库
`sudo yum install cairo cairo-devel cairomm-devel libjpeg-turbo-devel pango pango-devel pangomm pangomm-devel giflib-devel`

2. 安装依赖
`npm install --production`

3. 执行程序
`npm start`

4. 进入安装程序
 http://localhost:3000/admin/install
`localhost`和`3000`是你的服务器地址和你启动程序时的端口，默认是3000

关于使用 pm2 托管传程序和 nginx 反向代理等帮助，请移步 http://www.nodercms.com/help
