### ISSUE TITLE
foreach循环内调用上级变量

### ISSUE THREAD

**Issue by mhsnet** [welkinwong/nodercms#7]
{{#features 'rc-home-solution'}}
				{{#foreach extensions.pic}}
				<a href="{{url}}" style="background-image: url('{{src}}')">
				{{/foreach}}
			{{/features}}

**Comment by welkinwong** [comment]
你好可以详细描述一下你的问题吗？

**Comment by mhsnet** [comment]
上面这段中{{url}}无效，推荐中定义的字段

**Comment by welkinwong** [comment]
你可以通过../来访问上级变量，比如说'{{../src}}
