### ISSUE TITLE
使用体验

### ISSUE THREAD

**Issue by zzzzail** [welkinwong/nodercms#9]
老铁做的超级好
各种分离
像极了php的很成熟的项目
不过有一点就是async包有点过时
没有用上es6新特性 async/await 这样会没有更多的回调嵌套
非常感谢作者

**Comment by welkinwong** [comment]
谢谢夸奖~ 主要是当时建这个项目时比较早，而且一直比较稳定所以没有怎么重构（主要是懒），后续会继续迭代，请多关注哦 : )
